language: r

r:
  - release
  - devel
  - oldrel

sudo: required
cache:
  - packages
  - ccache

latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r_packages:
  - devtools
  - testthat
  - roxygen2
  - covr

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov()'
